### PR TITLE
add svelte-domain

### PR DESCRIPTION
**Pull request by thegenius**
### svelte-domain is a library for svelte state management with following features:
1. Small: Zero dependencies and really small, only 1.26KB and gziped 624B
2. Clean: Only 2 API you should learn, createModel, createStore.
3. Support async: Naturally async support you will dream about after using writable.
4. Cool typescript support: You can enjoy all the good parts of typescript.
5. Elegant: clean concepts inspired by elm, dva, redux and rematch

### CODE REVIEW

**Comment by TheComputerM** [comment]
Svelte-Domain is not a framework, please put it under appropriate category.

**Comment by thegenius** [comment]
> Svelte-Domain is not a framework, please put it under appropriate category.

I wonder if it is appropriate to add a state manager library category？

**Comment by TheComputerM** [comment]
LGTM, please add the state management section to the table of contents and if possible, add other state managements libs which you find 'awesome' to the list.

**Comment by thegenius** [comment]
> LGTM, please add the state management section to the table of contents and if possible, add other state managements libs which you find 'awesome' to the list.

alreay add a new section and add svelte-asyncable

**Pull request merged**
