### PR TITLE
Add svelte-frappe-charts

### PR DESCRIPTION
**Pull request by himynameisdave**
Adds ﻿[`svelte-frappe-charts`](https://github.com/himynameisdave/svelte-frappe-charts).

Also: should we add a charts category? There are [other](https://www.npmjs.com/package/@carbon/charts-svelte) charting libraries for Svelte.

### CODE REVIEW

**Comment by TheComputerM** [comment]
Yeah, for sure we need a charts category, was dumb of me to forget.

**Comment by himynameisdave** [comment]
Would you like me to add a **Charts** section in this PR then?

**Comment by TheComputerM** [comment]
Yeah that would be great.

**Comment by himynameisdave** [comment]
@TheComputerM done!

**Comment by TheComputerM** [comment]
Thank you very much :+1:.

**Pull request merged**
